version: 0.0
os: linux

files:
  # S3에 저장한 파일들 중 destination(AWS EC2)으로 이동시킬 대상을 지정한다.
  # / 이라고 지정하면 S3에 저장한 전체 파일을 뜻한다.
  - source: /								#S3의 root를 의미함...> 전체 파일을 의미 함...
    # EC2의 어떤 경로에 저장할 지 지정한다. 
    destination: /home/ubuntu/spring-git-github	

permissions:
  - object: /
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/start-server.sh	
      timeout: 60
      runas: ubuntu